return {
  -- 'akinsho/bufferline.nvim',
  -- version = '*',
  -- dependencies = 'nvim-tree/nvim-web-devicons',
  -- config = function()
  --   require('bufferline').setup {
  --     options = {
  --       offsets = {
  --         {
  --           filetype = 'neo-tree',
  --           text = 'File Explorer',
  --           text_align = 'center',
  --         },
  --       },
  --       separator_style = 'slant',
  --       show_buffer_close_icons = true,
  --       show_close_icon = true,
  --       show_tab_indicators = true,
  --     },
  --   }
  -- end,
}
